# config.yaml

max_results: 100 # max number of results shown
past_days: 20 # number of days to check from today
sorting: ['date', 'scirate'] # possible options: title, date, scirate, category
sorting_rev: true # true: descending order, false: ascending order
all_sections: false # check all categories?
run_scirate: false # fetch scirates?
literal: true # literal search of keywords

# andor vars decide how to search for keyauthors and keywords
# they can take the value "+OR+", "+AND+", "+ANDNOT+"
# "+OR+" -> select all the results with ANY of the keys
# "+AND+" -> select all the results with ALL the keys
# "+ANDNOT+" -> select all the result with none of the keys
and_or_sections: "+OR+"
and_or_keyauthors: "+OR+"
and_or: "+OR+"
and_or_keywords: "+OR+"

keys:
    # if you do not want to specify some keys, put [00]
    # DO NOT leave the brackets blank []
    sections: [math.AT, math.NA, math.CO, cs.LG, cs.CC, cs.CG, quant-ph]
    keyauthors: [coles, babbush, cirac]
    keywords: [nisq, adiabatic]

# additional keys: vqa, encoding