# config.yaml

max_results: 100 # max number of results shown
past_days: 20 # number of days to check from today
# past_days: 36525 # to search all the arxiv (for old papers or when arxiv_sortorder is ascending)
literal: true # literal search of keywords
run_scirate: false # fetch scirates?

# sorting entries in arxiv API
# how the entries are sorted BEFORE fetching them:
# descending -> FETCH new papers first
# ascending -> FETCH old papers first (also see past_days for old papers)
arxiv_sortby: "submittedDate" # "relevance", "lastUpdatedDate"
arxiv_sortorder: "descending" # "ascending"

# sorting entries in speed-the-arxiv
# how the entries are sorted (and shown) AFTER fetching them:
# descending -> SHOW new papers first
# ascending -> SHOW old papers first
sortby: ['date', 'scirate'] # possible options: title, date, scirate, category
sortorder_rev: true # true: descending order, false: ascending order

# andor vars decide how to search for keyauthors and keywords
# they can take the value "+OR+", "+AND+", "+ANDNOT+"
# "+OR+" -> select all the results with ANY of the keys
# "+AND+" -> select all the results with ALL the keys
# "+ANDNOT+" -> select all the result with none of the keys
and_or_sections: "+OR+"
and_or_keyauthors: "+OR+"
and_or: "+OR+"
and_or_keywords: "+OR+"

keys:
<<<<<<< Updated upstream
    # if you do not want to specify some keys, leave the list empty []
    sections: [math.NA, cs.LG, cs.CC, cs.CG, quant-ph]
    keyauthors: [coles, babbush, cirac]
    keywords: [nisq, adiabatic]
=======
    # if you do not want to specify some keys, put [00]
    # DO NOT leave the brackets blank []
    sections: [math.AT, math.NA, math.CO, cs.LG, cs.CC, cs.CG, quant-ph]
    keyauthors: [coles,babbush,schuld,cerezo,larocca,rudolph,holmes]
    keywords: [nisq,quantum machine learning,topological data analysis,quantum circuit expressibility,quantum circuit expressivity,geometric quantum machine learning,unitary evolution,quantum subspace expansion,quantum feature map,quantum encoding,topological data analysis,quantum convolutional neural networks,quantum signal processing,bqp problems]
>>>>>>> Stashed changes

# additional keys: vqa, encoding